# Generated by Django 4.2.4 on 2023-08-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='myuser',
            table='users',
        ),
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
    ]
