# Generated by Django 4.2.3 on 2023-07-20 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('created_as', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'notes',
                'managed': True,
            },
        ),
    ]
