# Generated by Django 4.2.3 on 2023-07-20 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True, validators=[django.core.validators.MinLengthValidator(4), django.core.validators.MaxLengthValidator(32)])),
                ('password', models.TextField(validators=[django.core.validators.MinLengthValidator(8), django.core.validators.MaxLengthValidator(32)])),
                ('email', models.CharField(validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
    ]
