# Generated by Django 4.2.3 on 2023-07-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True, 'verbose_name': 'Замітку', 'verbose_name_plural': 'Замітки'},
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created_as',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=32, verbose_name='Назва'),
        ),
    ]
